[package]
name = "lender"
version = "0.1.4"
edition = "2021"
authors = ["Lance Warden <wanderlanz@proton.me>"]
license = "MIT OR Apache-2.0"
description = "Lending iterator based on implicitly-restricted higher-ranked lifetimes"
repository = "https://github.com/WanderLanz/Lender"

[badges]
maintenance = { status = "experimental" }

[dependencies]
