[package]
name = "lender"
version = "0.2.4"
edition = "2021"
authors = ["Lance Warden <wanderlanz@proton.me>", "Sebastiano Vigna <sebastiano.vigna@gmail.com>"]
license = "Apache-2.0 OR LGPL-2.1-or-later OR MIT"
description = "iter feature complete(-ish) lending iterator"
repository = "https://github.com/WanderLanz/Lender"
categories = ["rust-patterns", "no-std"]
keywords = ["lending", "iterator"]

[badges]
maintenance = { status = "experimental" }

[dependencies]
lender-derive = { version = "0.1.0", optional = true }

[features]
default = ["derive"]
derive = ["lender-derive"]
